# Generated by Django 3.1.1 on 2020-09-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery_aaron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='Photo/'),
        ),
    ]
