# Generated by Django 3.1.1 on 2020-09-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery_aaron', '0005_auto_20200919_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
