# Generated by Django 3.1.1 on 2020-09-20 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo_gallery_aaron', '0007_auto_20200920_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='gallery_photos', to='photo_gallery_aaron.Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='photo_gallery_aaron.gallery'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
